### ISSUE TITLE
`onClose` callback not working

### ISSUE THREAD

**Issue by pauloFernandes** [douglasjunior/react-recaptcha-that-works#2]
Whenever I try using `onClose` callback in my recaptcha, it fails because there is no parent node for recaptcha challenge iframe.

To be more specific, the problem is that when the app searches for this window's iframe, this object was not already created.

**Comment by douglasjunior** [comment]
You need to handle the `onLoad` callback to know when the recaptcha is ready to use. 
You cant call "execute" before "onLoad" is called.

Please, provide some example code to your issue description.

**Comment by pauloFernandes** [comment]
Don't know if this is the problem, because my error only appears when I use the `onClose` callback, and, using `onLoad`, its callback works properly, before the error in `onClose`.

I described what I'm doing and what's happening [here](https://github.com/douglasjunior/react-recaptcha-that-works/pull/3#issuecomment-556374268)

**Comment by vishalj** [comment]
This seems to be happening as well. Debugging the code it seems the url is changed 
![Screenshot 2024-10-14 at 2 16 27 PM](https://github.com/user-attachments/assets/92f36c50-207e-44ab-ac4c-13aff526e6f0)

But the lib is searching for `if (iframe.src.includes('google.com/recaptcha/api2/bframe')) {` 
which is causing 
![Screenshot 2024-10-14 at 2 17 18 PM](https://github.com/user-attachments/assets/1327845b-8122-4b5f-b449-9ef0c46ec783)

Changing the `bframe` to `anchor` seems to work. But feel this can break again. Would be better to remove that word completely so future changes don't break this
