### ISSUE TITLE
Recaptcha Cannot read properties of undefined errors

### ISSUE THREAD

**Issue by MikhailR1337** [douglasjunior/react-recaptcha-that-works#5]
- Browser - google chrome
- "react": "^18.2.0",
- react-recaptcha-that-works: "^2.0.1",
- Did the problem happen after updating the library? - No
- Are you using the library for the first time? - yes
- It's a bug? - I have an error: TypeError: Cannot read properties of undefined (reading 'clients') (the first screenshot) after successfully solving Recaptcha I call nextjs router method.push -> router.push(url, undefined, { shallow: true }) and got it.

Investigated source code I found a solution -> unmount before using router.push -> but if I after that I try to come back to prev page I have another error TypeError: Cannot read properties of undefined (reading 'badge') (the second screenshot)

How can I overcome it?

<img width="909" alt="image" src="https://github.com/douglasjunior/react-recaptcha-that-works/assets/72802785/19388700-ee6b-4302-863c-c808367e1a77">
<img width="486" alt="image" src="https://github.com/douglasjunior/react-recaptcha-that-works/assets/72802785/40282ba5-2d39-4fd8-b825-2732c3be4adc">

**Comment by douglasjunior** [comment]
This file in stack trace `recaptcha_en.js` is not from the `react-recaptcha-that-works` itself. Seems to be a file from inside reCAPTCHA SDK.

I never see these type of errors before, here we use the component in pages that are mounted and unmounted by `react-router` with no problems.

![recaptcha](https://github.com/douglasjunior/react-recaptcha-that-works/assets/1512341/14ab299f-1ad5-4f72-b338-5a30fd8503ee)

**Comment by MikhailR1337** [comment]
@douglasjunior Thank you, it really looks like the problem has to do with GoogleReCaptchaProvider from 'react-google-recaptcha-v3'

**Comment by douglasjunior** [comment]
Oh, I have never used recaptcha v3 before, so I can't make sure that it will work with the library.
