### ISSUE TITLE
I can't change the style of the recpatcha widget

### ISSUE THREAD

**Issue by pedrokasak** [douglasjunior/react-recaptcha-that-works#6]
how can i modify the width of the recpatcha so that i can occupy the entire width of my div and make it so that when the recaptcha is finished the widget doesn't disappear but stays with the checked one, because any modification i make doesn't change the recaptcha widget.

I don't want to use it as a modal, but rather fit it into a form.

**Comment by douglasjunior** [comment]
The official customization available in Google reCAPTCHA is described in the props list https://github.com/douglasjunior/react-recaptcha-that-works?tab=readme-ov-file#props

Any additional customization is not guaranteed to work because Google can change their CSS and breaks everything.

**Comment by pedrokasak** [comment]
![image](https://github.com/douglasjunior/react-recaptcha-that-works/assets/14133553/37648607-30f9-4904-b415-27b94ba09922)

**Comment by douglasjunior** [comment]
Wait, are you talking about `react-recaptcha-that-works` or `react-NATIVE-recaptcha-that-works`? 😄

**Comment by pedrokasak** [comment]
react-NATIVE-recaptcha-that-works
