### ISSUE TITLE
[React Native 0.76]: Does this library support the new architecture?

### ISSUE THREAD

**Issue by OmkarK45** [douglasjunior/react-recaptcha-that-works#8]
Hi! 
Thank you for creating this library :)

I am upgrading an app to React Native 0.76. Can you comment on the new architecture support status? Is this compatible with new architecture?

**Comment by douglasjunior** [comment]
This library is only for web, not for React Native.

**Comment by OmkarK45** [comment]
Sorry, mistook it for the similar one on mobile
